TITLE = 'Sea Battle'
VERSION = '0.7.3'
AUTHOR = 'Aunmag'

CELL_SHIP_UNIT = 'D'
CELL_SHIP_DAMAGED = 'x'
CELL_SHIP_DESTROYED = '#'
CELL_SPACE_EMPTY = '.'
CELL_SPACE_HIT = '*'
CELL_SPACE_BUFFER = '^'

X_AXIS_DIRECTED = 0
Y_AXIS_DIRECTED = 1
